config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations], path: '', path_names: { sign_in: "admin", sign_out: "logout"}
  resources :users
  resources :homes
  resources :events
  resources :singles
  resources :albums
  resources :radioshows
  resources :people

  get 'simple_pages/index'
  root "simple_pages#index"

  get "/music", to: "simple_pages#music"

  get "/sign_up" => redirect("/")

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def index
  end

  def music
  	@albums = Album.order(:created_at).reverse
  	@singles = Single.order(:created_at).reverse
  end
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/views/simple_pages/index.html.erb
<div class="container-fluid hero-img" style="background-image: url(<%= Home.first.background_image_url %>);">
	<%= image_tag(Home.first.overlay_image_url, class: "img-responsive video-overlay", style: "mix-blend-mode: " + Home.first.overlay_image_blend_mode + ";") %>
</div>

<div class="container blurb">
	<p><%= Home.first.text %></p>
	
	<% if user_signed_in? %>
		<button class="listen"><%= link_to 'Edit', edit_home_path(Home.first) %></button>
	<% end %>
</div>

<!-- <div class="container-fluid hero-img">
  <img src="img/gb_neon.jpg" class="img-responsive video-overlay">
</div> -->

app/views/simple_pages/music.html.erb
<div class="header">
  <h1>Music</h1>
</div>

<div class="wrap">
  
  <!-- // RADIO -->

	<div class="container radio-show">

		<div class="row">
			<div class="col-sm-12 col-md-6 music-img match">
        <div class="placeholder-square">
          <%= image_tag(Radioshow.first.image_url, class: "img-responsive") %>
        </div>
			</div>
      <div class="col-sm-12 col-md-6 modal-info match" id="radio_match">
      	<h2><%= Radioshow.first.title %></h2>
      	<h3><%= Radioshow.first.episode %></h3>
      	<h4>Hosted by Melvo Baptiste</h4>
        <p class="contains-test"><%= simple_format(Radioshow.first.description) %></p>
        <button class="listen"><%= link_to "Listen Now", Radioshow.first.listen_url %></button>

        <% if user_signed_in? %>
          <button class="listen"><%= link_to 'Edit', edit_radioshow_path(Radioshow.first) %></button>
        <% end %>
        
        <div class="socials music-socials mob-hide">
					<h3>Follow Us</h3>
            <%= link_to image_tag("socials/sp_blk.svg"), "https://open.spotify.com/user/defected.records/playlist/5x1wgnYy9bbDhzRBpqSxq5" %>
			    	<%= link_to image_tag("socials/ap_blk.svg"), "https://itunes.apple.com/gb/playlist/glitterbox-disco-house-by-defected-records/pl.bc5b982882c845aeafae9a4a45066530?at=11lEW&ct=g2medp" %>
			    	<%= link_to image_tag("socials/sc_blk.svg"), "https://soundcloud.com/glitterboxibiza" %>
			    	<%= link_to image_tag("socials/yt_blk.svg"), "https://www.youtube.com/user/glitterboxibiza" %>
				</div>
			</div>
		</div>
		
	</div>
	<!-- RADIO // -->

	<!-- // ALBUMS -->

	<div class="container singles">
		<h2>Albums</h2>

		<!-- // Thumbnails -->
		<div class="row">

			<% @albums.each_with_index do |album, index| %>
				<div class="col-xs-12 col-sm-6 col-md-4 single match">
          <div class="placeholder-square">
					 <%= link_to image_tag(album.image_url.thumb, class: "img-responsive"), "#lightbox", data: { toggle: "modal", slide_to: index} %>
          </div>
				</div>
			<% end %>

      <% if user_signed_in? %>
        <div class="col-xs-12 col-sm-6 col-md-4 single match">
          <%= link_to image_tag("black.png", class: "img-responsive", style: "width:100%;"), new_album_path %>
          <span class="add"><span class="plus">+</span><br>New Album</span>
        </div>
      <% end %>
			


		</div><!-- row // -->
		<!-- Thumbnails // -->

		<!-- // modal carousel -->
    <div class="modal fade and carousel slide" id="lightbox">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-body">
            <div class="carousel-inner" id="people-modals">


              <% @albums.each do |album| %>
              <!-- // ALBUM BLOCK -->
              <div class="item <%= " active" if album == @albums.first %>">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                <div class="row">
                  <div class="col-sm-12 col-md-6  modal-img"><%= image_tag(album.image_url, class: "img-responsive") %></div>
                  <div class="col-sm-12 col-md-6 modal-info">
                    <h2><%= album.title %></h2>
                      <p><%= simple_format(album.description) %></p>
				              <div class="buy-links">
						            <% if album.listen_url != "" %>
						              <button><%= link_to "Listen", album.listen_url %></button>
						            <% end %>
						            <% if album.cd_buy_url != "" %>
						              <button><%= link_to album.cd_button_text, album.cd_buy_url %></button>
						            <% end %>
						            <% if album.vinyl_buy_url != "" %>
						              <button><%= link_to album.vinyl_button_text, album.vinyl_buy_url %></button>
						            <% end %>
                        <% if user_signed_in? %>
						              <button><%= link_to 'Edit', edit_album_path(album) %></button>
						              <button><%= link_to 'Delete', album, method: :delete, data: { confirm: 'Are you sure?' } %></button>
                        <% end %>
						          </div>               
                  </div>
                </div>
              </div>
              <!-- ALBUM BLOCK // -->
              <% end %>

            </div><!-- /.carousel-inner -->
            <a class="left carousel-control" href="#lightbox" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-triangle-left"></span>
            </a>
            <a class="right carousel-control" href="#lightbox" role="button" data-slide="next">
              <span class="glyphicon glyphicon-triangle-right"></span>
            </a>
          </div><!-- /.modal-body -->
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <!-- modal carousel -->



	</div><!-- container // -->
	<!-- ALBUMS // -->

	<!-- // SINGLES -->

	<div class="container singles">
		<h2>Singles</h2>

		<!-- // Thumbnails -->
		<div class="row">

			<% @singles.each_with_index do |single, index| %>
				<div class="col-xs-6 col-md-4 col-lg-3 single match">
          <div class="placeholder-square">
					 <%= link_to image_tag(single.image_url.thumb, class: "img-responsive"), "#lightbox-singles", data: { toggle: "modal", slide_to: index} %>
          </div>
				</div>
			<% end %>

      <% if user_signed_in? %>
  			<div class="col-xs-6 col-md-4 col-lg-3 single match">
  				<%= link_to image_tag("black.png", class: "img-responsive", style: "width:100%;"), new_single_path %>
  				<span class="add"><span class="plus">+</span><br>New Single</span>
  			</div>
      <% end %>

		</div><!-- row // -->
		<!-- Thumbnails // -->

		<!-- // modal carousel -->
    <div class="modal fade and carousel slide" id="lightbox-singles">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-body">
            <div class="carousel-inner" id="people-modals">


              <% @singles.each do |single| %>
              <!-- // ALBUM BLOCK -->
              <div class="item <%= " active" if single == @singles.first %>">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                <div class="row">
                  <div class="col-sm-12 col-md-6  modal-img"><%= image_tag(single.image_url.url, class: "img-responsive") %></div>
                  <div class="col-sm-12 col-md-6 modal-info">
                    <h2><%= single.artist %></h2>
                    <h3><%= single.title %></h3>
                    <p><%= simple_format(single.description) %></p>
			              <div class="buy-links">
					            <% if single.listen_url != "" %>
					              <button><%= link_to "Listen", single.listen_url %></button>
					            <% end %>
					            <% if single.vinyl_buy_url != "" %>
					              <button><%= link_to single.vinyl_button_text, single.vinyl_buy_url %></button>
					            <% end %>
                      <% if user_signed_in? %>
					             <button><%= link_to 'Edit', edit_single_path(single) %></button>
					             <button><%= link_to 'Delete', single, method: :delete, data: { confirm: 'Are you sure?' } %></button>
                     <% end %>
					          </div>               
                  </div>
                </div>
              </div>
              <!-- ALBUM BLOCK // -->
              <% end %>

            </div><!-- /.carousel-inner -->
            <a class="left carousel-control" href="#lightbox-singles" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-triangle-left"></span>
            </a>
            <a class="right carousel-control" href="#lightbox-singles" role="button" data-slide="next">
              <span class="glyphicon glyphicon-triangle-right"></span>
            </a>
          </div><!-- /.modal-body -->
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <!-- modal carousel -->

	</div><!-- container // -->

	<!-- SINGLES // -->
	
</div><!-- wrap // -->