config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations], path: '', path_names: { sign_in: "admin", sign_out: "logout"}
  resources :users
  resources :homes
  resources :events
  resources :singles
  resources :albums
  resources :radioshows
  resources :people

  get 'simple_pages/index'
  root "simple_pages#index"

  get "/music", to: "simple_pages#music"

  get "/sign_up" => redirect("/")

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/single.rb
class Single < ApplicationRecord
	validates :title, presence: true
	validates :artist, presence: true
	validates :description, presence: true
	validates :image_url, presence: true

	mount_uploader :image_url, SingleUploader
end

app/controllers/singles_controller.rb
class SinglesController < ApplicationController
  before_action :set_single, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /singles
  # GET /singles.json
  def index
    redirect_to music_path
  end

  # GET /singles/1
  # GET /singles/1.json
  def show
    redirect_to music_path
  end

  # GET /singles/new
  def new
    @single = Single.new
  end

  # GET /singles/1/edit
  def edit
  end

  # POST /singles
  # POST /singles.json
  def create
    @single = Single.new(single_params)

    respond_to do |format|
      if @single.save
        format.html { redirect_to music_path, notice: 'Single was successfully created.' }
        format.json { render :show, status: :created, location: @single }
      else
        format.html { render :new }
        format.json { render json: @single.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /singles/1
  # PATCH/PUT /singles/1.json
  def update
    respond_to do |format|
      if @single.update(single_params)
        format.html { redirect_to music_path, notice: 'Single was successfully updated.' }
        format.json { render :show, status: :ok, location: @single }
      else
        format.html { render :edit }
        format.json { render json: @single.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /singles/1
  # DELETE /singles/1.json
  def destroy
    @single.destroy
    respond_to do |format|
      format.html { redirect_to music_path, notice: 'Single was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_single
      @single = Single.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def single_params
      params.require(:single).permit(:title, :artist, :description, :image_url, :listen_url, :cd_buy_url, :cd_button_text_url, :vinyl_buy_url, :vinyl_button_text)
    end
end

app/helpers/singles_helper.rb
module SinglesHelper
end

app/views/singles/_form.html.erb
<%= form_with(model: single, local: true) do |form| %>
  <% if single.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(single.errors.count, "error") %> prohibited this single from being saved:</h2>

      <ul>
      <% single.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field row">
    <div class="col-xs-3"><%= form.label :title %>*</div>
    <div class="col-xs-9"><%= form.text_field :title, id: :single_title %></div>
  </div>

  <div class="field row">
    <div class="col-xs-3"><%= form.label :artist %>*</div>
    <div class="col-xs-9"><%= form.text_field :artist, id: :single_artist %></div>
  </div>

  <div class="field row">
    <div class="col-xs-3"><%= form.label :description %>*</div>
    <div class="col-xs-9"><%= form.text_area :description, id: :single_description %></div>
  </div>

  <div class="field row">
    <div class="col-xs-3"><%= form.label :image_url %>*</div>
    <div class="col-xs-9"><%= form.file_field :image_url, id: :single_image_url %></div>
  </div>

  <div class="field row">
    <div class="col-xs-3"><%= form.label :listen_url %></div>
    <div class="col-xs-9"><%= form.text_field :listen_url, id: :single_listen_url %></div>
  </div>

  <div class="field row">
    <div class="col-xs-3"><%= form.label :vinyl_buy_url %></div>
    <div class="col-xs-9"><%= form.text_field :vinyl_buy_url, id: :single_vinyl_buy_url %></div>
  </div>

  <div class="field row">
    <div class="col-xs-3"><%= form.label :vinyl_button_text %></div>
    <div class="col-xs-9"><%= form.select :vinyl_button_text, ["", "Buy Vinyl", "Pre-Order Vinyl"], id: :single_vinyl_buy_url %></div>
  </div>

  <div class="row">
    <div class="col-xs-3"></div>
    <div class="col-xs-9">
      <div class="actions">
        <%= form.submit %>
      </div>
    </div>
  </div>

<% end %>

app/views/singles/edit.html.erb
<h1>Editing Single</h1>

<div class="wrap">
	<div class="container edit-form">
		<%= render 'form', single: @single %>
		<div class="row">
	    <div class="col-xs-3"></div>
	    <div class="col-xs-9">
			<%= link_to 'Back', music_path %>
	    </div>
	  </div>
	</div>
</div>

app/views/singles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Singles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Artist</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Vinyl buy url</th>
      <th>Vinyl button text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @singles.each do |single| %>
      <tr>
        <td><%= single.title %></td>
        <td><%= single.artist %></td>
        <td><%= single.description %></td>
        <td><%= single.image_url %></td>
        <td><%= single.vinyl_buy_url %></td>
        <td><%= single.vinyl_button_text %></td>
        <td><%= link_to 'Show', single %></td>
        <td><%= link_to 'Edit', edit_single_path(single) %></td>
        <td><%= link_to 'Destroy', single, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Single', new_single_path %>

app/views/singles/new.html.erb
<h1>New Single</h1>

<div class="wrap">
	<div class="container edit-form">
		<%= render 'form', single: @single %>
		<div class="row">
	    <div class="col-xs-3"></div>
	    <div class="col-xs-9">
			<%= link_to 'Back', music_path %>
	    </div>
	  </div>
	</div>
</div>

app/views/singles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @single.title %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @single.artist %>
</p>

<p>
  <strong>Description:</strong>
  <%= @single.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @single.image_url %>
</p>

<p>
  <strong>Vinyl buy url:</strong>
  <%= @single.vinyl_buy_url %>
</p>

<p>
  <strong>Vinyl button text:</strong>
  <%= @single.vinyl_button_text %>
</p>

<%= link_to 'Edit', edit_single_path(@single) %> |
<%= link_to 'Back', singles_path %>